### ISSUE TITLE
prusa: Поставить на панельку энкодер.

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/Marlin#3]
Сабж. С кликом. Для того, чтобы управлять принтером без подключения к компьютеру.

**Comment by jekhor** [comment]
Готово.

**Comment by abitrolly** [comment]
Что за энкодер с кликом?

**Comment by jekhor** [comment]
http://belchip.by/product/?selected_product=11399

**Comment by abitrolly** [comment]
Так бы сразу и сказал - крутёлку для ручного управления, а клик, чтобы пасту выдавливать. Но надо же два, так?
